name: unico_check
description: Esta biblioteca visa implementar a tecnologia unico check na plataforma flutter.
version: 4.23.0
homepage: https://github.com/acesso-io/unico_check_flutter

environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.unico_check
        pluginClass: UnicoCheckPlugin
      ios:
        pluginClass: UnicoCheckPlugin